language: csharp
sudo: false
dist: trusty
mono:
  - 5.2.0
  - 5.0.0
os:
  - linux
  - osx
osx_image: xcode8.2
solution: ZmopSharp.sln
install:
  - nuget restore ZmopSharp.sln
script:
  - msbuild /p:Configuration=Release